/*
 * Stack definitions for canfd - generated by CANopen DeviceDesigner 2.5.0
 * Di. Sep. 27 10:28:06 2016
 */

/* protect against multiple inclusion of the file */
#ifndef GEN_DEFINE_H
#define GEN_DEFINE_H 1

/* some information about the tool that has generated this file */
#define GEN_TOOL_NAME	CANOPEN_DEVICEDESIGNER
#define GEN_TOOL_VERSION	0x020500ul

/* Line Settings */
#define CO_MULTI_LINE_CNT	1u
#define CANOPEN_SUPPORTED	1u
/* Number of objects per line */
#define CO_OBJECTS_LINE_0_CNT	22u
#define CO_OBJECT_COUNTS	22u
#define CO_COB_COUNTS	9u
#define CO_TXPDO_COUNTS	1u
#define CO_RXPDO_COUNTS	1u
#define CO_SSDO_COUNTS	1u
#define CO_CSDO_COUNTS	1u
#define CO_ASSIGN_COUNTS	0u
#define CO_GUARDING_COUNTS	CO_ASSIGN_COUNTS
#define CO_ERR_CTRL_COUNTS	0u
#define CO_ERR_HIST_COUNTS	1u
#define CO_EMCY_CONS_COUNTS	0u
#define CO_NODE_IDS	node
#define CO_NODE_ID_FUNCTIONS NULL

/* Definition of numbers of CANopen services */
#define CO_CANFD_SUPPORTED	1u
#define CO_SDO_SERVER_CNT	1u
#define CO_SDO_CLIENT_CNT	1u
#define CO_PDO_TRANSMIT_CNT	1u
#define CO_PDO_RECEIVE_CNT	1u
#define CO_MAX_MAP_ENTRIES	8u
#define CO_TR_PDO_DYN_MAP_ENTRIES	1u
#define CO_EMCY_PRODUCER	1u
#define CO_EMCY_ERROR_HISTORY 1u
#define CO_SDO_QUEUE		1u
#define CO_SDO_QUEUE_LEN	10u
/* number of used COB objects */
#define CO_COB_CNT	9u


/* Definition of number of call-back functions for each service*/
#define CO_EVENT_DYNAMIC_SDO_SERVER_READ	1u
#define CO_EVENT_DYNAMIC_SDO_SERVER_WRITE	1u
#define CO_EVENT_DYNAMIC_SDO_SERVER_CHECK_WRITE	1u
#define CO_EVENT_DYNAMIC_PDO	1u
#define CO_EVENT_DYNAMIC_NMT	1u
#define CO_EVENT_DYNAMIC_ERRCTRL	1u
#define CO_EVENT_DYNAMIC_CAN	1u
#define CO_EVENT_DYNAMIC_SDO_CLIENT_READ	1u
#define CO_EVENT_DYNAMIC_SDO_CLIENT_WRITE	1u
#define CO_EVENT_DYNAMIC_EMCY	1u
#define CO_EVENT_DYNAMIC_SDO_SERVER_DOMAIN_WRITE	1u
#define CO_SDO_SERVER_DOMAIN_CNT	5u

/* Definition of CAN queue sizes */
#define CO_CONFIG_REC_BUFFER_CNT	5u
#define CO_CONFIG_TRANS_BUFFER_CNT	5u

/* application-specific defines as defined in CANopen DeviceDesigner */
extern unsigned char node;
#define CO_USDO_SUPPORTED 1
/* end of application-specific defines */

/* Hardware settings */
/*  */
#define CO_TIMER_INTERVAL	10000u

/* do not modify comments starting with 'user-specific section:' */
/* user-specific section: start */

/* can4linux */
#define C4L_DEVICE	"/dev/can0"

/* SocketCAN device */
#define CAN_INTERFACE 	"can0"
#define CO_CANFD_SUPPORTED 1
#define CO_USDO_SUPPORTED 1

#if defined CO_CANFD_SUPPORTED
# define CANFD	1
# define CO_CANFD_SDO_SUPPORTED	1
#endif

unsigned char getNodeId(void);
/* user-specific section: end */

#endif /* GEN_DEFINE_H */
