/*
 * CANopen static indication definitions for slave_t - generated by CANopen DeviceDesigner 2.7.0
 * 周四 十一月 2 16:31:43 2017
 */

/* protect against multiple inclusion of the file */
#ifndef GEN_INDICATION
#define GEN_INDICATION 1

/* 
   There are not any static indication functions defined.
   If there were some, they would be declared here. 
 */

#endif /* GEN_INDICATION*/
