/*
 * CANopen static indication definitions for master1_b - generated by CANopen DeviceDesigner 2.7.0
 * 周五 十月 13 09:28:40 2017
 */

/* protect against multiple inclusion of the file */
#ifndef GEN_INDICATION
#define GEN_INDICATION 1

/* 
   There are not any static indication functions defined.
   If there were some, they would be declared here. 
 */

#endif /* GEN_INDICATION*/
