/*
 * CANopen static indication definitions for slave1 - generated by CANopen DeviceDesigner 2.7.1.1
 * Mo Jun 26 16:31:44 2017
 */

/* protect against multiple inclusion of the file */
#ifndef GEN_INDICATION
#define GEN_INDICATION 1

/* 
   There are not any static indication functions defined.
   If there were some, they would be declared here. 
 */

#endif /* GEN_INDICATION*/
