/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "stdint.h"
#include "bsp.h"
#include "main.h"
#include "cmsis_os.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_GRAPH_0 (GUI_ID_USER + 0x01)
#define ID_LISTWHEEL_0 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_TEXT_3 (GUI_ID_USER + 0x04)
#define ID_GRAPH_1 (GUI_ID_USER + 0x05)
#define ID_BUTTON_0 (GUI_ID_USER + 0x06)
#define ID_TEXT_0 (GUI_ID_USER + 0x08)
#define ID_TEXT_1 (GUI_ID_USER + 0x09)
#define ID_BUTTON_1 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_2 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_3 (GUI_ID_USER + 0x0C)
extern const GUI_FONT GUI_Fontused_U48;
extern const GUI_FONT GUI_FontCalibri104;

extern const GUI_FONT GUI_Fontyahei;
uint16_t newWindow = 0;
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "display", ID_FRAMEWIN_0, 0, 0, 1024, 600, 0, 0x0, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 170, 11, 610, 260, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_0, 1612, 252, 50, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 10, 130, 150, 80, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_3, 10, 420, 155, 80, 0, 0x64, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_1, 170, 279, 610, 310, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 10, 55, 150, 70, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 10, 340, 150, 70, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 810, 30, 190, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 810, 180, 190, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 810, 330, 190, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 810, 480, 190, 100, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
static float tempRatio = 0.4*50;
static float humRatio = 1.0;
static float tempOffset = 50;
static GRAPH_DATA_Handle pdataTemp, pdataHumidity;
extern int16_t tempTh[2];
static WM_HWIN gHwn;//WM_GetDesktopWindow
float temp1 = 0;
float hum1 = 0;
void DISPLAY_DATA_DHT11(void)
{
	char temperature_s[10];
	char humidity_s[10];
	WM_HWIN hItem;
	WM_HWIN hWin = gHwn;

	float temp = tempTh[0]/10.0f;
	float hum = tempTh[1]/10.0f;
    /*****				温度数据				*******/
    snprintf(temperature_s,5, "%.1f", temp);
    snprintf(humidity_s,5, "%.1f", hum);

    hItem = WM_GetDialogItem(hWin, ID_TEXT_2);
    TEXT_SetText(hItem, temperature_s);
   // EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
   // EDIT_SetFont(hItem, GUI_FONT_32_ASCII);
    hItem = WM_GetDialogItem(hWin, ID_TEXT_3);
    /*****				湿度数据				*******/
    TEXT_SetText(hItem, humidity_s);
   // EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
  //  EDIT_SetFont(hItem, GUI_FONT_32_ASCII);

    GRAPH_DATA_YT_AddValue(pdataTemp, tempOffset + (int)(temp*tempRatio+0.5));
    GRAPH_DATA_YT_AddValue(pdataHumidity, (int)(hum*humRatio+0.5));
}


void SetWarningState(uint16_t state)
{
	WM_HWIN hItem = WM_GetDialogItem(gHwn, ID_BUTTON_3);
	if(state == 1)
	{
		BUTTON_SetFrameColor(hItem, GUI_RED);
		//BUTTON_SetTextColor
		BUTTON_SetBkColor(hItem, BUTTON_CI_DISABLED, GUI_RED);
		BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_RED);
		BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_RED);
	}
	else
	{
		BUTTON_SetFrameColor(hItem, GUI_GREEN);
		BUTTON_SetBkColor(hItem, BUTTON_CI_DISABLED, GUI_LIGHTGREEN);
		BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_LIGHTGREEN);
		BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_LIGHTGREEN);
	}
}

// USER START (Optionally insert additional static code)
// USER END

void SetIOState(uint16_t state)
{
	WM_HWIN hItem = WM_GetDialogItem(gHwn, ID_BUTTON_0);
	if(state == 1)
	{
		BUTTON_SetFrameColor(hItem, GUI_RED);
		//BUTTON_SetTextColor
		BUTTON_SetBkColor(hItem, BUTTON_CI_DISABLED, GUI_RED);
		BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_RED);
		BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_RED);
	}
	else
	{
		BUTTON_SetFrameColor(hItem, GUI_GREEN);
		BUTTON_SetBkColor(hItem, BUTTON_CI_DISABLED, GUI_LIGHTGREEN);
		BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_LIGHTGREEN);
		BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_LIGHTGREEN);
	}
}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	static uint16_t cuiShaoState = 0;
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  GRAPH_SCALE_Handle hScaleV, hScaleH;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'display'
    //
	  gHwn = pMsg->hWin;
    hItem = pMsg->hWin;
    FRAMEWIN_SetFont(hItem, GUI_FONT_32B_ASCII);
    FRAMEWIN_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    FRAMEWIN_SetTitleVis(hItem, 0);
    //
    // Initialization of 'Graph'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
    GRAPH_SetBorder(hItem,40, 5, 5, 30);
    GRAPH_SetGridVis(hItem,1);
    GRAPH_SetGridFixedX(hItem,1);
    GRAPH_SetGridDistY(hItem,25);
    GRAPH_SetGridDistX(hItem,50);
    GRAPH_SetVSizeY(hItem,100);
    GRAPH_SetVSizeX(hItem, 50);
    GRAPH_SetColor (hItem, GUI_DARKGREEN,   GRAPH_CI_GRID);
    hScaleV =GRAPH_SCALE_Create(40, GUI_TA_RIGHT, GRAPH_SCALE_CF_VERTICAL, 50);
    GRAPH_SCALE_SetTextColor(hScaleV,GUI_RED);
    GRAPH_SCALE_SetFont(hScaleV,GUI_FONT_24_ASCII);
    GRAPH_SCALE_SetOff(hScaleV, 50);
    GRAPH_SCALE_SetFactor(hScaleV,0.4f);
    tempRatio = 1.0f/0.4f;
    tempOffset = 50;

    GRAPH_AttachScale(hItem,hScaleV);

    hScaleH =GRAPH_SCALE_Create(235, GUI_TA_HCENTER, GRAPH_SCALE_CF_HORIZONTAL, 100);
    GRAPH_SCALE_SetFont(hScaleH,GUI_FONT_24_ASCII);
    GRAPH_SCALE_SetTextColor(hScaleH,GUI_RED);
    GRAPH_SCALE_SetFactor(hScaleH,0.1f);
    GRAPH_AttachScale(hItem,hScaleH);

    pdataTemp =GRAPH_DATA_YT_Create(GUI_LIGHTGREEN, 560, 0, 0);
    GRAPH_AttachData(hItem,pdataTemp);

    //GRAPH_DATA_XY_SetPenSize(hItem, 3);
    ///////////////////////////////**************************/////////////////
    hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_1);
    GRAPH_SetBorder(hItem,40, 5, 5, 30);
    GRAPH_SetGridVis(hItem,1);
    GRAPH_SetGridFixedX(hItem,1);
    GRAPH_SetGridDistY(hItem,25);
    GRAPH_SetGridDistX(hItem,50);
    GRAPH_SetVSizeY(hItem,100);
    GRAPH_SetVSizeX(hItem, 50);
    GRAPH_SetColor (hItem, GUI_DARKGREEN,   GRAPH_CI_GRID);
    hScaleV =GRAPH_SCALE_Create(40, GUI_TA_RIGHT, GRAPH_SCALE_CF_VERTICAL, 50);
    GRAPH_SCALE_SetTextColor(hScaleV,GUI_RED);
    GRAPH_SCALE_SetFont(hScaleV,GUI_FONT_24_ASCII);
    //GRAPH_SCALE_SetOff(hScaleV, 60);
    GRAPH_SCALE_SetFactor(hScaleV,0.4f);
    humRatio = 1.0f/0.4f;

    GRAPH_AttachScale(hItem,hScaleV);

    hScaleH =GRAPH_SCALE_Create(282, GUI_TA_HCENTER, GRAPH_SCALE_CF_HORIZONTAL, 100);
    GRAPH_SCALE_SetTextColor(hScaleH,GUI_RED);
    GRAPH_SCALE_SetFont(hScaleH,GUI_FONT_24_ASCII);
    GRAPH_SCALE_SetFactor(hScaleH,0.1f);
    GRAPH_AttachScale(hItem,hScaleH);
    pdataHumidity =GRAPH_DATA_YT_Create(GUI_LIGHTGREEN, 560/*最大数据个数*/, 0, 0);
    GRAPH_AttachData(hItem,pdataHumidity);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetText(hItem, "123");
    TEXT_SetFont(hItem, &GUI_FontCalibri104);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF00FF));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetText(hItem, "123");
    TEXT_SetFont(hItem, &GUI_FontCalibri104);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF0000));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_Fontused_U48);
    BUTTON_SetText(hItem, "吹  扫");
    //BUTTON_SetTextColor(hItem,BUTTON_CI_DISABLED, GUI_TRANSPARENT);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, &GUI_Fontused_U48);
    TEXT_SetText(hItem, "温  度");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, &GUI_Fontused_U48);
    TEXT_SetText(hItem, "湿  度");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_Fontused_U48);
    BUTTON_SetText(hItem, "历  史");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, &GUI_Fontused_U48);
    BUTTON_SetText(hItem, "设  置");

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, &GUI_Fontyahei);
    BUTTON_SetText(hItem, "报 警");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_LISTWHEEL_0: // Notifications sent by 'Listwheel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_TEXT_2: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_TEXT_3: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
    	   hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    	   if(cuiShaoState == 0)
    	   {
    		//   BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_RED);
    		   cuiShaoState = 1;
    		   osMessagePut(MB_MAINSTEP, (uint32_t) IO_STATE_ON, 0);
    	   }
    	   else
		   {
    		 //  WM_HWIN hItem1 = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    		//   BUTTON_SetBkColor(hItem,BUTTON_CI_UNPRESSED, BUTTON_GetBkColor(hItem1, BUTTON_CI_UNPRESSED));
    		   cuiShaoState = 0;
    		   osMessagePut(MB_MAINSTEP, (uint32_t) IO_STATE_OFF, 0);
		   }
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
    	  newWindow = 3;
    	  // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
    	  newWindow = 2;
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
    case ID_BUTTON_3: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        // USER START (Optionally insert additional code for further Ids)
        // USER END
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Createdisplay
*/

WM_HWIN allUI[3]={0,0,0,};

WM_HWIN Createdisplay(void);
WM_HWIN Createdisplay(void) {
 // WM_HWIN hWin;

	allUI[0] = gHwn = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
//  WM_CreateTimer(WM_GetClientWindow(gHwn), 0, 450, 0);	    //添加此段
  return gHwn;
}
void StartUIMain(uint16_t typ)
{
	//WM_DeleteTimer(0);
	if(typ == 1)
	{
		WM_HideWindow(allUI[2]);
		WM_HideWindow(allUI[1]);
		WM_ShowWindow(allUI[0]);
	}
	else
		WM_ShowWindow(allUI[0]);
	WM_SetCallback(WM_HBKWIN, &_cbDialog);
	WM_HWIN hItem = WM_GetDialogItem(WM_HBKWIN, ID_BUTTON_0);
	if( prvReadBackupRegister(MANUAL_STATE) != 0)
	{
		WM_EnableWindow(hItem);
	}
	else
	{
		WM_DisableWindow(hItem);

	}
}
// USER START (Optionally insert additional public code)
#define NUMBYTES_NEEDED   0x200000
extern uint16_t uiStarted;
void Tsk(void*p)
{
	long int NumFreeBytes = GUI_ALLOC_GetNumFreeBytes();

	if (NumFreeBytes > NUMBYTES_NEEDED)
	{
		//WM_SetCreateFlags(WM_CF_MEMDEV);
		WM_SetCreateFlags(WM_CF_MEMDEV);

		Createdisplay();
		CreateSetting();
		Createhistory();
		uiStarted = 1;
		newWindow = 1;
		while (1)
		{
			if(newWindow == 1)
			{
				newWindow = 0;
				StartUIMain(1);
			}
			else if (newWindow == 2)
			{
				newWindow = 0;
				StartUISetting(1);
			}
			else if (newWindow == 3)
			{
				newWindow = 0;
				StartHistory();
			}
			GUI_Exec();
			osDelay(5);
		}
//	GUI_ExecDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);

	}
}

void AddData(int x0, int x1)
{
	static unsigned int i =0;
	GUI_MULTIBUF_Begin();
	for (int j=0; j<5;j++)
	{
	i++;

	GRAPH_DATA_YT_AddValue(pdataTemp, (i%70)*3+80);
	GRAPH_DATA_YT_AddValue(pdataHumidity, (i%100)*3+10);

	}
	GUI_MULTIBUF_End();
}

// USER END

/*************************** End of file ****************************/
