/*
 * def.h
 *
 *  Created on: 2019Äê3ÔÂ26ÈÕ
 *      Author: pli
 */

#ifndef INC_DEF_H_
#define INC_DEF_H_



enum
{
	ISR_PRIORITY_TICK		= 15,
	ISR_PRIORITY_ETH		= 7,
	ISR_PRIORITY_USB		= 14,
	ISR_PRIORITY_CAN		= 9,
	ISR_PRIORITY_TIM6		= 6,
	ISR_PRIORITY_ADC1 		= 5,
	ISR_PRIORITY_UART       = 12,
	ISR_PRIORITY_USART_DMA  = 12,
	ISR_PRIORITY_SDIO 		= 4,
	ISR_PRIORITY_SDIO_DMA   = 5,
	ISR_PRIORITY_TIMER		= 8,
};

/*  */
enum
{
	ISR_SUB_PRIORITY_TICK		= 0,
	ISR_SUB_PRIORITY_I2C2DMA	= 0,
	ISR_SUB_PRIORITY_I2C2_ER	= 8,
	ISR_SUB_PRIORITY_I2C2_EV 	= 9,


	ISR_SUB_PRIORITY_SPI2  		= 0,
	ISR_SUB_PRIORITY_SPI5  		= 8,

	ISR_SUB_PRIORITY_ADC1 		= 0,
	ISR_SUB_PRIORITY_ADC3	 	= 1,
	ISR_SUB_PRIORITY_CAN1_TX	= 0,
	ISR_SUB_PRIORITY_CAN1_RX	= 1,
	ISR_SUB_PRIORITY_CAN1_SCE	= 2,
	ISR_SUB_PRIORITY_CAN2_TX	= 3,
	ISR_SUB_PRIORITY_CAN2_RX	= 4,
	ISR_SUB_PRIORITY_CAN2_SCE	= 5,
	ISR_SUB_PRIORITY_EXIT		= 0,


	ISR_SUB_PRIORITY_UART_DMA	= 0,
	ISR_SUB_PRIORITY_UART       = 8,
	ISR_SUB_PRIORITY_TIMER      = 0,
	ISR_SUB_PRIORITY_AD_TIMER   = 0,
};



#endif /* INC_DEF_H_ */
